# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
