# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dance_types',
            field=models.ManyToManyField(blank=True, to='entities.DanceType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_types',
            field=models.ManyToManyField(blank=True, to='entities.EventType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='links',
            field=models.ManyToManyField(blank=True, to='entities.Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('PL', 'Заплонировано'), ('DN', 'Отменено'), ('PP', 'Перенесено'), ('HL', 'Проведено')], default='PL', max_length=2),
        ),
    ]
