# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.Location'),
        ),
    ]
