# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20170421_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone_number', models.CharField(blank=True, max_length=50)),
                ('message_subject', models.CharField(max_length=100)),
                ('message_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('PL', 'Запланировано'), ('DN', 'Отменено'), ('PP', 'Перенесено'), ('HL', 'Проводится'), ('CL', 'Завершено')], default='PL', max_length=2),
        ),
    ]
