# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20170502_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='is_opened_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
