# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_danceclass_is_opened_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='is_probably_free',
            field=models.BooleanField(default=False),
        ),
    ]
