# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20170504_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancehall',
            name='links',
            field=models.ManyToManyField(blank=True, to='entities.Link'),
        ),
        migrations.AddField(
            model_name='danceshop',
            name='links',
            field=models.ManyToManyField(blank=True, to='entities.Link'),
        ),
    ]
