# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20170505_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancehall',
            name='location',
        ),
        migrations.RemoveField(
            model_name='danceshop',
            name='location',
        ),
        migrations.AddField(
            model_name='dancehall',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.Location'),
        ),
        migrations.AddField(
            model_name='danceshop',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.Location'),
        ),
    ]
