# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0013_auto_20170505_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinkfb',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sociallinkinstagram',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sociallinktwitter',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sociallinkvk',
            name='author',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='vk',
        ),
        migrations.DeleteModel(
            name='SocialLinkFB',
        ),
        migrations.DeleteModel(
            name='SocialLinkInstagram',
        ),
        migrations.DeleteModel(
            name='SocialLinkTwitter',
        ),
        migrations.DeleteModel(
            name='SocialLinkVK',
        ),
    ]
