# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_auto_20170505_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractSocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='SocialLinkFB',
            fields=[
                ('abstractsociallink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractSocialLink')),
            ],
            bases=('entities.abstractsociallink',),
        ),
        migrations.CreateModel(
            name='SocialLinkInstagram',
            fields=[
                ('abstractsociallink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractSocialLink')),
            ],
            bases=('entities.abstractsociallink',),
        ),
        migrations.CreateModel(
            name='SocialLinkTwitter',
            fields=[
                ('abstractsociallink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractSocialLink')),
            ],
            bases=('entities.abstractsociallink',),
        ),
        migrations.CreateModel(
            name='SocialLinkVK',
            fields=[
                ('abstractsociallink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractSocialLink')),
            ],
            bases=('entities.abstractsociallink',),
        ),
        migrations.AddField(
            model_name='abstractsociallink',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile'),
        ),
        migrations.AddField(
            model_name='socials',
            name='fb',
            field=models.ManyToManyField(blank=True, to='entities.SocialLinkFB'),
        ),
        migrations.AddField(
            model_name='socials',
            name='instagram',
            field=models.ManyToManyField(blank=True, to='entities.SocialLinkInstagram'),
        ),
        migrations.AddField(
            model_name='socials',
            name='twitter',
            field=models.ManyToManyField(blank=True, to='entities.SocialLinkTwitter'),
        ),
        migrations.AddField(
            model_name='socials',
            name='vk',
            field=models.ManyToManyField(blank=True, to='entities.SocialLinkVK'),
        ),
    ]
