# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20170505_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='author',
        ),
        migrations.RemoveField(
            model_name='location',
            name='dance_types',
        ),
        migrations.AlterField(
            model_name='dancehall',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.AbstractLocation'),
        ),
        migrations.AlterField(
            model_name='danceshop',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.AbstractLocation'),
        ),
        migrations.AlterField(
            model_name='dancestudio',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.AbstractLocation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.AbstractLocation'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
