# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20170505_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationInMap',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.Location')),
            ],
            bases=('entities.location',),
        ),
        migrations.RemoveField(
            model_name='location',
            name='dance_types',
        ),
        migrations.RemoveField(
            model_name='location',
            name='show_in_map_section',
        ),
    ]
