# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_auto_20170508_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('show_in_map_section', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile')),
                ('dance_types', models.ManyToManyField(blank=True, to='entities.DanceType')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PlaceInMapLocation',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLocation')),
            ],
            bases=('entities.abstractlocation',),
        ),
        migrations.AddField(
            model_name='placeinmap',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.PlaceInMapLocation'),
        ),
    ]
