# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_auto_20170508_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationinmap',
            name='dance_types',
            field=models.ManyToManyField(blank=True, to='entities.DanceType'),
        ),
        migrations.AddField(
            model_name='locationinmap',
            name='show_in_map_section',
            field=models.BooleanField(default=False),
        ),
    ]
