# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0017_auto_20170508_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationInMap',
            new_name='PlaceInMap',
        ),
    ]
