# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0017_auto_20170508_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceHallLocation',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLocation')),
            ],
            bases=('entities.abstractlocation',),
        ),
        migrations.CreateModel(
            name='DanceShopLocation',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLocation')),
            ],
            bases=('entities.abstractlocation',),
        ),
        migrations.CreateModel(
            name='DanceStudioLocation',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLocation')),
            ],
            bases=('entities.abstractlocation',),
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLocation')),
            ],
            bases=('entities.abstractlocation',),
        ),
        migrations.AlterField(
            model_name='dancehall',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.DanceHallLocation'),
        ),
        migrations.AlterField(
            model_name='danceshop',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.DanceShopLocation'),
        ),
        migrations.AlterField(
            model_name='dancestudio',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.DanceStudioLocation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.EventLocation'),
        ),
    ]
