# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0018_auto_20170508_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractMapCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='placeinmap',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='DanceHallMapCoordinates',
            fields=[
                ('abstractmapcoordinates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractMapCoordinates')),
            ],
            bases=('entities.abstractmapcoordinates',),
        ),
        migrations.CreateModel(
            name='DanceShopMapCoordinates',
            fields=[
                ('abstractmapcoordinates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractMapCoordinates')),
            ],
            bases=('entities.abstractmapcoordinates',),
        ),
        migrations.CreateModel(
            name='DanceStudioMapCoordinates',
            fields=[
                ('abstractmapcoordinates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractMapCoordinates')),
            ],
            bases=('entities.abstractmapcoordinates',),
        ),
        migrations.CreateModel(
            name='PlaceInMapMapCoordinates',
            fields=[
                ('abstractmapcoordinates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractMapCoordinates')),
            ],
            bases=('entities.abstractmapcoordinates',),
        ),
        migrations.AddField(
            model_name='abstractmapcoordinates',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile'),
        ),
        migrations.AddField(
            model_name='dancehalllocation',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.DanceHallMapCoordinates'),
        ),
        migrations.AddField(
            model_name='danceshoplocation',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.DanceShopMapCoordinates'),
        ),
        migrations.AddField(
            model_name='dancestudiolocation',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.DanceStudioMapCoordinates'),
        ),
        migrations.AddField(
            model_name='placeinmaplocation',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.PlaceInMapMapCoordinates'),
        ),
    ]
