# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_auto_20170508_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancehall',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Contacts'),
        ),
        migrations.AddField(
            model_name='danceshop',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Contacts'),
        ),
        migrations.AddField(
            model_name='dancestudio',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Contacts'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Contacts'),
        ),
    ]
