# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0023_auto_20170508_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('NEW', 'Начинающий'), ('INM', 'Средний'), ('ADV', 'Опытный'), ('SHW', 'Шоу'), ('PRC', 'Практика'), ('OTH', 'Другое')], max_length=3),
        ),
    ]
