# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0024_danceclass_experience_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DanceType',
            new_name='DanceStyle',
        ),
    ]
