# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0025_auto_20170509_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danceclass',
            old_name='dance_types',
            new_name='dance_styles',
        ),
        migrations.RenameField(
            model_name='dancestudio',
            old_name='dance_types',
            new_name='dance_styles',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='dance_types',
            new_name='dance_styles',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='dance_types',
            new_name='dance_styles',
        ),
        migrations.RenameField(
            model_name='placeinmap',
            old_name='dance_types',
            new_name='dance_styles',
        ),
    ]
