# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0001_initial'),
        ('entities', '0026_auto_20170509_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danceclass',
            name='schedule_week_days',
        ),
        migrations.AddField(
            model_name='dancestyle',
            name='average_prices',
            field=models.ManyToManyField(blank=True, to='dance_styles.AveragePrice'),
        ),
        migrations.AddField(
            model_name='dancestyle',
            name='between_partners_distances',
            field=models.ManyToManyField(blank=True, to='dance_styles.BetweenPartnersDistance'),
        ),
        migrations.AddField(
            model_name='dancestyle',
            name='count_types',
            field=models.ManyToManyField(blank=True, to='dance_styles.CountType'),
        ),
        migrations.AddField(
            model_name='dancestyle',
            name='dance_direction',
            field=models.CharField(choices=[('BAL', 'Балет'), ('LAT', 'Латина')], default='LAT', max_length=3),
        ),
        migrations.AddField(
            model_name='dancestyle',
            name='for_children',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
    ]
