# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_weekday'),
        ('entities', '0027_auto_20170510_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='schedule_week_days',
            field=models.ManyToManyField(blank=True, to='classes.WeekDay'),
        ),
    ]
