# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0028_danceclass_schedule_week_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='AbstractLink',
        ),
    ]
