# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0029_auto_20170512_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClassLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='DanceHallLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='DanceShopLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='DanceStudioLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='InstructorLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='links',
            field=models.ManyToManyField(blank=True, to='entities.DanceClassLink'),
        ),
        migrations.AlterField(
            model_name='dancehall',
            name='links',
            field=models.ManyToManyField(blank=True, to='entities.DanceHallLink'),
        ),
        migrations.AlterField(
            model_name='danceshop',
            name='links',
            field=models.ManyToManyField(blank=True, to='entities.DanceShopLink'),
        ),
        migrations.AlterField(
            model_name='dancestudio',
            name='links',
            field=models.ManyToManyField(blank=True, to='entities.DanceStudioLink'),
        ),
        migrations.AlterField(
            model_name='event',
            name='links',
            field=models.ManyToManyField(blank=True, to='entities.EventLink'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='links',
            field=models.ManyToManyField(blank=True, to='entities.InstructorLink'),
        ),
    ]
