# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0030_auto_20170512_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractShouldKnow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='LinkShouldKnowLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='OrganizationShouldKnowLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='PersonShouldKnowLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='LinkShouldKnow',
            fields=[
                ('abstractshouldknow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractShouldKnow')),
                ('links', models.ManyToManyField(blank=True, to='entities.LinkShouldKnowLink')),
            ],
            bases=('entities.abstractshouldknow',),
        ),
        migrations.CreateModel(
            name='OrganizationShouldKnow',
            fields=[
                ('abstractshouldknow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractShouldKnow')),
                ('links', models.ManyToManyField(blank=True, to='entities.OrganizationShouldKnowLink')),
            ],
            bases=('entities.abstractshouldknow',),
        ),
        migrations.CreateModel(
            name='PersonShouldKnow',
            fields=[
                ('abstractshouldknow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractShouldKnow')),
                ('links', models.ManyToManyField(blank=True, to='entities.PersonShouldKnowLink')),
            ],
            bases=('entities.abstractshouldknow',),
        ),
        migrations.AddField(
            model_name='abstractshouldknow',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile'),
        ),
    ]
