# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0031_auto_20170512_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dancestyle',
            old_name='dance_direction',
            new_name='direction',
        ),
    ]
