# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0032_auto_20170512_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkshouldknow',
            name='direction',
            field=models.CharField(choices=[('OTH', 'Другое')], default='OTH', max_length=3),
        ),
        migrations.AddField(
            model_name='organizationshouldknow',
            name='direction',
            field=models.CharField(choices=[('OTH', 'Другое')], default='OTH', max_length=3),
        ),
        migrations.AddField(
            model_name='personshouldknow',
            name='direction',
            field=models.CharField(choices=[('OTH', 'Другое')], default='OTH', max_length=3),
        ),
    ]
