# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0033_auto_20170512_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AbstractWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AudioWikiLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='VideoWikiLink',
            fields=[
                ('abstractlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLink')),
            ],
            bases=('entities.abstractlink',),
        ),
        migrations.CreateModel(
            name='AudioWiki',
            fields=[
                ('abstractwiki_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractWiki')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.AudioWikiLink')),
            ],
            bases=('entities.abstractwiki',),
        ),
        migrations.CreateModel(
            name='AudioWikiTag',
            fields=[
                ('abstracttag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractTag')),
            ],
            bases=('entities.abstracttag',),
        ),
        migrations.CreateModel(
            name='VideoWiki',
            fields=[
                ('abstractwiki_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractWiki')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.VideoWikiLink')),
            ],
            bases=('entities.abstractwiki',),
        ),
        migrations.CreateModel(
            name='VideoWikiTag',
            fields=[
                ('abstracttag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractTag')),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
            ],
            bases=('entities.abstracttag',),
        ),
        migrations.AddField(
            model_name='abstractwiki',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile'),
        ),
        migrations.AddField(
            model_name='abstractwiki',
            name='dance_styles',
            field=models.ManyToManyField(blank=True, to='entities.DanceStyle'),
        ),
        migrations.AddField(
            model_name='videowiki',
            name='tags',
            field=models.ManyToManyField(blank=True, to='entities.VideoWikiTag'),
        ),
        migrations.AddField(
            model_name='audiowiki',
            name='tags',
            field=models.ManyToManyField(blank=True, to='entities.AudioWikiTag'),
        ),
    ]
