# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0034_auto_20170514_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiowiki',
            name='song_author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
