# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0037_auto_20170515_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoWikiAlbum',
            fields=[
                ('abstractwikigroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractWikiGroup')),
                ('photos', models.ManyToManyField(blank=True, to='entities.PhotoWiki')),
            ],
            bases=('entities.abstractwikigroup',),
        ),
    ]
