# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0038_photowikialbum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiowikiplaylist',
            name='audios',
        ),
        migrations.RemoveField(
            model_name='videowikiplaylist',
            name='videos',
        ),
        migrations.AlterField(
            model_name='audiowikiplaylist',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.AudioWikiPlaylistLink'),
        ),
        migrations.AlterField(
            model_name='videowikiplaylist',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.VideoWikiPlaylistLink'),
        ),
    ]
