# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0040_auto_20170515_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_date',)},
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(choices=[('FEST', 'Фестивать'), ('COMP', 'Конкурс'), ('MCLS', 'Мастер-класс'), ('OAIR', 'Open air'), ('PART', 'Вечеринка')], default='MCLS', max_length=4),
        ),
    ]
