# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0043_abstracttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_types',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
