# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0044_auto_20170519_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClassType',
            fields=[
                ('abstracttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractType')),
                ('title', models.CharField(choices=[('GRUP', 'Групповые занятия'), ('OPLS', 'Открытый урок')], default='GRUP', max_length=4)),
            ],
            bases=('entities.abstracttype',),
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('abstracttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractType')),
                ('title', models.CharField(choices=[('FEST', 'Фестивать'), ('COMP', 'Конкурс'), ('MCLS', 'Мастер-класс'), ('OAIR', 'Open air'), ('PART', 'Вечеринка')], default='MCLS', max_length=4)),
            ],
            bases=('entities.abstracttype',),
        ),
        migrations.AddField(
            model_name='event',
            name='event_types',
            field=models.ManyToManyField(blank=True, to='entities.EventType'),
        ),
    ]
