# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0045_auto_20170519_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='dance_class_types',
            field=models.ManyToManyField(blank=True, to='entities.DanceClassType'),
        ),
    ]
