# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0046_danceclass_dance_class_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danceclass',
            name='is_opened_lesson',
        ),
    ]
