# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0047_remove_danceclass_is_opened_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClassPriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('PAID', 'Платно'), ('FREE', 'Бесплатно'), ('SHWR', 'Условно-бесплатно'), ('FLRF', 'Первое занятие бесплатно')], default='PAID', max_length=4)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='danceclass',
            name='every_first_lesson_free',
        ),
        migrations.RemoveField(
            model_name='danceclass',
            name='first_lesson_free',
        ),
        migrations.RemoveField(
            model_name='danceclass',
            name='free_lesson_date',
        ),
        migrations.RemoveField(
            model_name='danceclass',
            name='is_probably_free',
        ),
        migrations.AddField(
            model_name='danceclass',
            name='price_types',
            field=models.ManyToManyField(blank=True, to='entities.DanceClassPriceType'),
        ),
    ]
