# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0048_auto_20170519_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClassExperienceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('NEW', 'Начинающий'), ('INM', 'Средний'), ('ADV', 'Опытный'), ('SHW', 'Шоу'), ('PRC', 'Практика')], default='NEW', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='danceclass',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='danceclass',
            name='experience_levels',
            field=models.ManyToManyField(blank=True, to='entities.DanceClassExperienceLevel'),
        ),
    ]
