# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0052_auto_20170523_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='status',
            field=models.CharField(blank=True, choices=[('PL', 'Запланировано'), ('DN', 'Отменено'), ('PP', 'Перенесено'), ('HL', 'Проводится'), ('CL', 'Завершено')], default='PL', max_length=2),
        ),
    ]
