# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0053_danceclass_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractlocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dancehall',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='danceshop',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='dancestudio',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='event',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='placeinmap',
            name='locations',
        ),
    ]
