# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0054_auto_20170523_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractlocation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.City'),
        ),
    ]
