# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0055_abstractlocation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancehall',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.DanceHallLocation'),
        ),
        migrations.AddField(
            model_name='danceshop',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.DanceShopLocation'),
        ),
        migrations.AddField(
            model_name='dancestudio',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.DanceStudioLocation'),
        ),
        migrations.AddField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.EventLocation'),
        ),
        migrations.AddField(
            model_name='placeinmap',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.PlaceInMapLocation'),
        ),
    ]
