# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0056_auto_20170523_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
