# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0057_danceclass_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('abstracttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractType')),
                ('title', models.CharField(choices=[('OADP', 'Open air вечеринки')], default=(('OADP', 'Open air вечеринки'),), max_length=4)),
            ],
            bases=('entities.abstracttype',),
        ),
        migrations.AddField(
            model_name='placeinmap',
            name='place_types',
            field=models.ManyToManyField(blank=True, to='entities.PlaceType'),
        ),
    ]
