# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0058_auto_20170524_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='title',
            field=models.CharField(choices=[('OADP', 'Open air')], default=(('OADP', 'Open air'),), max_length=4),
        ),
    ]
