# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0060_auto_20170524_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceshop',
            name='shop_types',
            field=models.ManyToManyField(blank=True, to='entities.ShopType'),
        ),
    ]
