# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0061_danceshop_shop_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorLocation',
            fields=[
                ('abstractlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.AbstractLocation')),
            ],
            bases=('entities.abstractlocation',),
        ),
        migrations.AddField(
            model_name='instructor',
            name='locations',
            field=models.ManyToManyField(blank=True, to='entities.InstructorLocation'),
        ),
    ]
