# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0002_dancestyleinsectionattendeeage_dancestyleinsectionaverageprice_dancestyleinsectionbetweenpartnersdis'),
        ('entities', '0062_auto_20170525_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceStyleDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BAL', 'Балет'), ('LAT', 'Латина')], default='LAT', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DanceStyleInSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('video', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attendee_ages', models.ManyToManyField(blank=True, to='dance_styles.DanceStyleInSectionAttendeeAge')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.UserProfile')),
                ('average_prices', models.ManyToManyField(blank=True, to='dance_styles.DanceStyleInSectionAveragePrice')),
                ('between_partners_distances', models.ManyToManyField(blank=True, to='dance_styles.DanceStyleInSectionBetweenPartnersDistance')),
                ('count_types', models.ManyToManyField(blank=True, to='dance_styles.DanceStyleInSectionCountType')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='average_prices',
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='between_partners_distances',
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='count_types',
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='for_children',
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='image',
        ),
        migrations.AlterField(
            model_name='dancestyle',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.DanceStyleDirection'),
        ),
        migrations.AddField(
            model_name='dancestyleinsection',
            name='dance_style',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.DanceStyle'),
        ),
    ]
