# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AveragePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, choices=[('LOW', 'Низкая'), ('AVG', 'Средняя'), ('HIG', 'Высокая')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BetweenPartnersDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(blank=True, choices=[('CLS', 'Близкое'), ('AVG', 'Среднее'), ('DIS', 'Далекое')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_type', models.CharField(blank=True, choices=[('SOL', 'Одиночный'), ('PRN', 'Парный'), ('GRP', 'Групповой')], max_length=3)),
            ],
        ),
    ]
