# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceStyleInSectionAttendeeAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_age', models.CharField(blank=True, choices=[('CHD', 'Дети'), ('MXD', 'Смешанная группа'), ('GUP', 'Взрослые')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DanceStyleInSectionAveragePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, choices=[('LOW', 'Низкая'), ('AVG', 'Средняя'), ('HIG', 'Высокая')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DanceStyleInSectionBetweenPartnersDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(blank=True, choices=[('CLS', 'Близкое'), ('AVG', 'Среднее'), ('DIS', 'Далекое')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DanceStyleInSectionCountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_type', models.CharField(blank=True, choices=[('SOL', 'Одиночный'), ('PRN', 'Парный'), ('GRP', 'Групповой')], max_length=3)),
            ],
        ),
    ]
